# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create(title: "Ruby")
Category.create(title: "Java")
Category.create(title: "HTML")

User.create(name: “Paul“, email: “paul@mail.com“)
User.create(name: “John“, email: “john@mail.com“)
User.create(name: “Matt“, email: “matt@mail.com“)
User.create(name: “Mary“, email: “mary@mail.com“)
User.create(name: “Caroline“, email: “caroline@mail.com“)

Test.create (title: "Test1", level: 1, category_id 1, author_id: 1)
Test.create (title: "Test2", level: 2, category_id 3, author_id: 4)
Test.create (title: "Test3", level: 1, category_id 2, author_id: 1)
Test.create (title: "Test4" level: 1, category_id 1, author_id: 2)

Question.create (title: "Which is the file extension for saving the ruby file?", test_id: 1)
Question.create (title: "….syntax matches with Ruby syntax", test_id: 1)
Question.create (title: "Ruby is an object oriented general purpose programming language", test_id: 1)
Question.create (title: "What does .upcase method do?", test_id: 4)
Question.create (title: "What does the 1...10 indicate?", test_id: 4)
Question.create (title: "Correct HTML tag for the largest heading is", test_id: 2)
Question.create (title: "All HTML tags must be enclosed in?", test_id: 2)
Question.create (title: "Choose the correct HTML tag to make a text Italic", test_id: 2)
Question.create (title: "In which file database table configuration is stored?", test_id: 3)
Question.create (title: "Which of the following functions is used to find and fix bugs in the Java programs?", test_id: 3)
Question.create (title: "...is the return type of the hashCode() method in the Object class?", test_id: 3)

Answer.create (title: ".rb", correct: true, question_id: 1)
Answer.create (title: ".ruby", correct: false, question_id: 1)
Answer.create (title: ".rrb", correct: false, question_id: 1)
Answer.create (title: "None of the above", correct: false, question_id: 1)
Answer.create (title: "Java", correct: false, question_id: 2)
Answer.create (title: "PHP", correct: false, question_id: 2)
Answer.create (title: "Perl", correct: true, question_id: 2)
Answer.create (title: "None of the above", correct: flase, question_id: 2)
Answer.create (title: "true", correct: true, question_id: 3)
Answer.create (title: "false", correct: false, question_id: 3)
Answer.create (title: "Convert the string to lowercase", correct: false, question_id: 4)
Answer.create (title: "Convert the string to uppercase", correct: true, question_id: 4)
Answer.create (title: "Convert only lovercase string to uppercase and vice-versa", correct: false, question_id: 4)
Answer.create (title: "None of the above", correct: false, question_id: 4)
Answer.create (title: "Inclusive range", correct: false, question_id: 5)
Answer.create (title: "Exclusive range", correct: true, question_id: 5)
Answer.create (title: "Both inclusive and exclusive range", correct: false, question_id: 5)
Answer.create (title: "None of above", correct: false, question_id: 5)
Answer.create (title: "<h6>", correct: false, question_id: 6)
Answer.create (title: "<heading>", correct: false, question_id: 6)
Answer.create (title: "<h1>", correct: true, question_id: 6)
Answer.create (title: "<head>", correct: false, question_id: 6)
Answer.create (title: "? and !", correct: false, question_id: 7)
Answer.create (title: "< and >", correct: true, question_id: 7)
Answer.create (title: "{ and }", correct: false, question_id: 7)
Answer.create (title: "# and #", correct: false, question_id: 7)
Answer.create (title: "<italic>", correct: false, question_id: 8)
Answer.create (title: "<it>", correct: false, question_id: 8)
Answer.create (title: "<i>", correct: true, question_id: 8)
Answer.create (title: "<il>", correct: false, question_id: 8)
Answer.create (title: ".sql", correct: false, question_id: 9)
Answer.create (title: ".ora", correct: false, question_id: 9)
Answer.create (title: ".hbm", correct: true, question_id: 9)
Answer.create (title: ".dbm", correct: false, question_id: 9)
Answer.create (title: "JVM", correct: false, question_id: 10)
Answer.create (title: "JDK", correct: false, question_id: 10)
Answer.create (title: "JRE", correct: false, question_id: 10)
Answer.create (title: "JDB", correct: true, question_id: 10)
Answer.create (title: "int", correct: true, question_id: 11)
Answer.create (title: "Object", correct: false, question_id: 11)
Answer.create (title: "void", correct: false, question_id: 11)
Answer.create (title: "long", correct: false, question_id: 11)

Result.create (user_id: 1, test_id:)
Result.create (user_id: 1, test_id:)
Result.create (user_id: 2, test_id:)
Result.create (user_id: 2, test_id:)
Result.create (user_id: 3, test_id:)
Result.create (user_id: 4, test_id:)
Result.create (user_id: 4, test_id:)
Result.create (user_id: 1, test_id:)
Result.create (user_id: 1, test_id:)
Result.create (user_id: 2, test_id:)
Result.create (user_id: 2, test_id:)
Result.create (user_id: 3, test_id:)
Result.create (user_id: 4, test_id:)
Result.create (user_id: 4, test_id:)